import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Buenisima",
            artist: "Buenisima",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ss1.audiorama.com.mx:6628/stream/1/",
            active: true,
        },
        {
            name:"La Mexiicana",
            artist: "LaMexiicana",
            cover: "https://img.freepik.com/vector-gratis/aire-letrero-neon-marco_23-2148818543.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://server3.sit-mexico.com:2199/proxy/mexicanaizucar?mp=/stream/1/",
            active: false,
        },
        {
            name:"Magia Digital",
            artist: "MagiaDigital",
            cover: "https://img.freepik.com/vector-gratis/fondo-musica_53876-90528.jpg",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://tv.radiohosting.online:8106/stream",
            active: false,
        },
        {
            name:"La Guadalupana",
            artist: "LaGuadalupana",
            cover: "https://img.freepik.com/vector-gratis/dia-mundial-radio-diseno-plano_23-2148802732.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://webprod.sipse.com.mx:8080/guadalupana",
            active: false,
        },
        {
            name:"La Z FM",
            artist: "LaZFM",
            cover: "https://img.freepik.com/vector-gratis/texto-plano-dia-mundial-radio_23-2148825802.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://24453.live.streamtheworld.com/XEQR_FMAAC_SC",
            active: false,
        },
        {
            name:"Radio Extremo Guila",
            artist: "RadioExtremoGuila",
            cover: "https://img.freepik.com/vector-gratis/ilustracion-realista-auriculares-inalambricos_1284-20763.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://sonic.xtremacomunicaciones.com.mx/8038/stream",
            active: false,
        },
        {   
            name:"La Cañona",
            artist: "La Cañona",
            cover: "https://img.freepik.com/foto-gratis/dispositivo-digital-inalambrico-auriculares-rosa_53876-96804.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://sp2.servidorrprivado.com/8112/stream",
            active: false,
        },
        {      
            name:"Ke Buena",
            artist: "KeBuena",
            cover: "https://img.freepik.com/psd-gratis/maqueta-microfono-escritorio-rectangular-vista-frontal_1332-10597.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://24413.live.streamtheworld.com/KEBUENA_SC",
            active: false,
        },
        {      
            name:"Banda",
            artist: "Banda",
            cover: "https://img.freepik.com/vector-gratis/concepto-marco-neon-aire_52683-52393.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://21933.live.streamtheworld.com/XHQQ_FM_SC",
            active: false,
        },
        {   
            name:"Bandolera",
            artist: "Bandolera",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41309.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26663.live.streamtheworld.com/XEBSAM_SC",
            active: false,
        },
        {   
            name:"La Lupe",
            artist: "LaLupe",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41314.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26483.live.streamLa mejor 103.7theworld.com/LACALIENTE_SC",
            active: false,
        },
        {      
            name:"La mejor FM",
            artist: "LamejorFM",
            cover: "https://img.freepik.com/foto-gratis/fondo-musica-o-podcast-auriculares-taza-cafe-mesa-azul-plana-vista-superior-plana_501050-983.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://26663.live.streamtheworld.com/XHTIM_SC",
            active: false,
        },
        {   
            name:"La Mejor 103.7",
            artist: "Lamejor103.7",
            cover: "https://img.freepik.com/vector-gratis/silueta-aparato-radio_23-2147501018.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://stream3.mexiserver.com:10055/stream/1/",
            active: false,
        },
    ];
}

export default chillHop;


